# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Work It' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Work It

  pod "DigitInputView"
  pod 'FloatingPanel'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyCodeView'
  pod 'Alamofire', '~> 4.9.1'
  pod 'DLRadioButton', '~> 1.4'
  pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git', :branch => 'master'
  pod 'LZViewPager', '~> 1.2.5'
  pod 'SDWebImage'
  pod 'AccountKit'
  pod 'lottie-ios'
  pod 'PostalAddressRow'
  pod 'ImageRow'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'Cosmos'
  pod 'GoogleSignIn'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/OAuth'
  pod 'FirebaseUI/Phone'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Analytics'

end
