# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Work It' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Work It

  pod "DigitInputView"

  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyCodeView'
  pod 'Alamofire', '~> 4.9.1'

  pod 'Toaster', :git => 'https://github.com/devxoul/Toaster.git', :branch => 'master'

  pod 'SDWebImage'
  pod 'lottie-ios'

  pod 'CHIPageControl', '~> 0.1.3'
  pod 'DateToolsSwift'
  pod 'SwiftPhotoGallery'

  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'Cosmos'
  pod 'GoogleSignIn', '5.0.0'

  pod 'FBSDKCoreKit', '9.0.0'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/OAuth'
  pod 'FirebaseUI/Phone'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Analytics'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
          end
      end
  end
  
end
